#!/bin/bash

# echo "commit_msg"

# path=$1
# echo path is $path

# a=$(cat $path)
# echo commit message is
# echo $a
# n=${#a}
# echo "length $n"
# if [[ "$a" =~ "hello world" ]];then
#   echo commit format test passed
#   exit 0
# else
#   echo commit format test failed
#   exit 1
# fi
maxMsgLength=122

if [[ $n -gt $maxMsgLength ]]; then
    echo "[commit-msg-hook] Your commit message exceeds the max characters length of $maxMsgLength. Please review the commit message."
fi

REGEX_ISSUE_ID="^(fix: |feat: |docs: |test: |chore: |ci: |perf: |style: |build: )(#([0-9])+)\s[a-zA-Z]+"
ISSUE_ID_IN_COMMIT=$(echo $(cat "$1") | grep -o -E "$REGEX_ISSUE_ID")

if [[ -z "$ISSUE_ID_IN_COMMIT" ]]; then
    BRANCH_NAME=$(git symbolic-ref --short HEAD)
    ISSUE_ID=$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID")

    if [[ -z "$ISSUE_ID" ]]; then
        echo "[commit-msg-hook] Your commit message is illegal. Please rename your branch with using following regex: $REGEX_ISSUE_ID"
        exit 1
    fi

    echo "$ISSUE_ID | $(cat "$1")" > "$1"
fi