name: TestsAndVersion

on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'

jobs:
  RunTests:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          cache: false

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Install dependencies
        run: go get .

      - name: Run tests
        run: gotestsum --format testname --format-hide-empty-pkg --format-hivis --junitfile ./junit.xml --junitfile-hide-empty-pkg --junitfile-testcase-classname short --junitfile-testsuite-name short

  CreateTag:
    if: github.event.pull_request.merged == true
    needs: RunTests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Get version
        run: echo "RELEASE_VERSION=$(go run . -v | cut -d " " -f 2)" >> $GITHUB_ENV
      
      - name: Create tag v${{ env.RELEASE_VERSION }}
        uses: negz/create-tag@v1
        with:
          token: '${{ secrets.ACTIONS_TOKEN }}'
          version: 'v${{ env.RELEASE_VERSION }}'
          message: ''
