name: VersionTag

on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'

jobs:
  CreateTag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get version
        run: echo "RELEASE_VERSION=$(go run . -v | cut -d " " -f 2)" >> $GITHUB_ENV
      
      - name: Create tag v${{ env.RELEASE_VERSION }}
        uses: negz/create-tag@v1
        with:
          token: '${{ secrets.GIT_TOKEN }}'
          version: 'v${{ env.RELEASE_VERSION }}'
          message: ''
