name: VersionTag

on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'

jobs:
  CreateTag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get version
        run: echo "RELEASE_VERSION=$(go run . -v | cut -d " " -f 2)" >> $GITHUB_ENV
      
      - name: Create tag v${{ env.RELEASE_VERSION }}
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          tag: "v${{ env.RELEASE_VERSION }}"
          force_push_tag: true