name: Release

on: [workflow_dispatch]

jobs:
  Release:

    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
        
      - name: Install dependencies
        run: go get .

      - name: Get version
        run: echo "RELEASE_VERSION=$(go run . -v | cut -d " " -f 2)" >> $GITHUB_ENV

      - name: Build Linux AMD 64
        run: env GOOS=linux GOARCH=amd64 go build -o ./build/ev-chargers-simulator-linux-amd64

      - name: Build Linux ARM 64
        run: env GOOS=linux GOARCH=arm64 GOARM=7 go build -o ./build/ev-chargers-simulator-linux-arm64

      - name: Create Linux AMD64 Artifact v${{ env.RELEASE_VERSION }}
        uses: actions/upload-artifact@v3
        with:
          name: EV Chargers Simulator Linux AMD64 v${{ env.RELEASE_VERSION }}
          path: build/ev-chargers-simulator-linux-amd64
          retention-days: 1

      - name: Create Linux ARM64 Artifact v${{ env.RELEASE_VERSION }}
        uses: actions/upload-artifact@v3
        with:
          name: EV Chargers Simulator Linux ARM64 v${{ env.RELEASE_VERSION }}
          path: build/ev-chargers-simulator-linux-arm64
          retention-days: 1
        
      - name: Install git-chglog
        run: go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest

      - name: Create changelog
        run: git-chglog --output changelog.md v${{ env.RELEASE_VERSION }}
        
      - name: Create changelog artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'changelog_v${{ env.RELEASE_VERSION }}.md'
          path: changelog.md
          retention-days: 5
          
      - name: Get release notes
        run: echo "RELEASE_NOTES=$(cat changelog.md)"#!/bin/bash

      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GIT_TOKEN }}
          tag: 'v${{ env.RELEASE_VERSION }}'
          name: 'v${{ env.RELEASE_VERSION }}'
          allow_override: true
          files: >
            build/ev-chargers-simulator-linux-amd64
            build/ev-chargers-simulator-linux-arm64
            changelog.md
          body: ${{ env.RELEASE_NOTES }}
